/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package money;

public class App {
    public static void main(String[] args) {
        System.out.println("I have got "+Money.dollar(10));
    }
}
